
version: '2.1.0.{build}'

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - git submodule update --init --recursive

cache:
  packages -> **\packages.config  

branches:
  only:
    - develop

skip_branch_with_pr: true

skip_tags: true

skip_commits:
  files:
    - '*.md'

before_build:
  - nuget sources add -name funcparser -source https://ci.appveyor.com/nuget/ospsuite-funcparser 
  - nuget sources add -name simmodel -source https://ci.appveyor.com/nuget/ospsuite-simmodel
  - nuget sources add -name cvodes -source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes-282
  - nuget restore -PackagesDirectory packages

build_script:
  - rake "create_setup[%APPVEYOR_BUILD_VERSION%]"

artifacts:
  - path: 'setup\deploy\*.msi'  
    name: 'package'

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=
